"""create leaves table

Revision ID: c8a4bfe6cc96
Revises: 9938daef191d
Create Date: 2026-08-22 13:21:52.504930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a4bfe6cc96'
down_revision: Union[str, None] = '9938daef191d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.Enum('PAID', 'SICK', 'UNPAID', name='leave_type'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='leave_status'), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('review_comment', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaves_employee_id'), 'leaves', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leaves_status'), 'leaves', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaves_status'), table_name='leaves')
    op.drop_index(op.f('ix_leaves_employee_id'), table_name='leaves')
    op.drop_table('leaves')
    # ### end Alembic commands ###
